DIRS = Dir.glob('**').select { |f| File.directory?(f) }

desc 'test all'
task :default => DIRS

DIRS.each do |d|
  desc "test #{d}"
  task d do
    cd d do
      sh "bundle exec ../../bin/sfrp --build=cc --out=compiled"
      sh './Main < in.txt | diff -y out.txt -'
      sh 'rm -fr ./compiled ./Main'
    end
  end
end
